server.port=8086
spring.application.name=core-service

# Database Configuration
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:atelier_db}?sslmode=prefer
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.naming.physical-strategy=com.forkdevs.driveos.platform.shared.infrastructure.persistence.jpa.configuration.strategy.SnakeCaseWithPluralizedTablePhysicalNamingStrategy
spring.jpa.show-sql=true

# JWT Security
authorization.jwt.secret=${JWT_SECRET:dGhpc2lzYXNlY3JldGtleWZvcmRyaXZlb3NwbGF0Zm9ybXNhYXNhcHBsaWNhdGlvbmluamF2YTI2}
