server.port=8081
spring.application.name=iam-service

# Database Configuration
spring.jpa.database=POSTGRESQL
spring.sql.init.platform=postgres
spring.datasource.url=jdbc:postgresql://${DATABASE_URL:localhost}:${DATABASE_PORT:5432}/${DATABASE_NAME:atelier_db}?sslmode=prefer
spring.datasource.username=${DATABASE_USER:postgres}
spring.datasource.password=${DATABASE_PASSWORD:postgres}

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME:dev}
spring.mail.password=${MAIL_PASSWORD:dev}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# JWT Configuration
authorization.jwt.secret=${JWT_SECRET:dGhpc2lzYXNlY3JldGtleWZvcmRyaXZlb3NwbGF0Zm9ybXNhYXNhcHBsaWNhdGlvbmluamF2YTI2}
authorization.jwt.expiration.days=30

# Application Settings
app.frontend.url=https://atelier-webapp-11848.vercel.app

# Google OAuth Configuration
google.client.id=${GOOGLE_CLIENT_ID:dummy-google-client-id}
