server.port=8080
spring.application.name=api-gateway

# Services Routing Configuration
services.iam.url=${IAM_SERVICE_URL:http://localhost:8081}
services.billing.url=${BILLING_SERVICE_URL:http://localhost:8082}
services.iot.url=${IOT_SERVICE_URL:http://localhost:8083}
services.operations.url=${OPERATIONS_SERVICE_URL:http://localhost:8084}
services.inventory.url=${INVENTORY_SERVICE_URL:http://localhost:8085}
services.core.url=${CORE_SERVICE_URL:http://localhost:8086}
services.fleet.url=${FLEET_SERVICE_URL:http://localhost:8087}

# JWT Security
authorization.jwt.secret=${JWT_SECRET:dGhpc2lzYXNlY3JldGtleWZvcmRyaXZlb3NwbGF0Zm9ybXNhYXNhcHBsaWNhdGlvbmluamF2YTI2}
